version: "3"
services:
  web:
    image: fcgomes92/nginx-node:latest
    build:
      context: ./
    ports:
      - "8080:80"
      - "3001:3000"
    environment: 
      - NODE_ENV=dev
    volumes:
      - ./:/app
      - /app/node_modules
