version: "3"
services:
  web:
    image: fcogmes92/drinks-web
    build:
      context: ./
    ports:
      - "8080:80"
    environment: 
      - NODE_ENV=dev
    volumes:
      - ./:/app
      - /app/node_modules
